version: "3"

services:
  web:
    build:
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - .:/app
    command: /app/startup.sh
    container_name: "${APP_NAME}_api"
    ports:
      - "${PORT}:8000"
    depends_on:
      - db
  db:
    container_name: "postgres_database"
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
volumes:
  postgres_data:
